yarnPath: .yarn/releases/yarn-4.0.2.cjs

injectEnvironmentFiles: [".env.yarn", ".env.local?"]

npmRegistries:
  "https://npm.pkg.github.com/":
    npmAlwaysAuth: true
    npmAuthToken: ${NODE_AUTH_TOKEN-''}
